# NTL模型配置文件
# 指定模型类和参数

# 模型类路径
model_class: WSADBench.baseline.NTL.run.NTL

# 模型参数
parameters:
  # 训练参数
  epochs: 100  # 论文里是100
#  batch_size: 489  # 论文里是数据集的5等分
  lr: 0.001
  step_size: 200
  gamma: 0.5
  train_method: 'loe_est'  # 论文里是loe_est
  query_method: 'kmeans'  # 论文里是kmeans
  query_num: 20 # 论文里是20,但rla过低时，会负样本不足（目前是负样本够的时候不用正样本。不够的时候，再用正样本补满）

  verbose: true
