# AABiGAN模型配置文件
# 指定模型类和参数

# 模型类路径
model_class: WSADBench.baseline.PReNet.run.PReNet

# 模型参数
parameters:
  # 训练参数
  epochs: 50
  batch_num: 20
  batch_size: 512
  lr: 0.001
  weight_decay: 0.01
  s_a_a: 8
  s_a_u: 4
  s_u_u: 0

# 其他参数
verbose: true
