# 模型类路径
model_class: WSADBench.baseline.ARNet.run.ARNet

# 模型参数
parameters:
  # 训练参数
  dropout: 0.7
  model_name: "model_single"  # 可选值: model_single, model_mean, model_sequence, model_concatcate
  epochs: 20
  batch_size: 30
  lr: 0.0001
  weight_decay:  0.0005
  # 损失权重
  DMIL_weight: 1.000
  Center_weight: 20.000
  # 其他
  # max_seqlen: 300 # 最大序列长度750
  segments_per_video: 32  # 每个视频的片段数
  k: 4

