# RoSAS模型配置文件
# 指定模型类和参数

# 模型类路径
model_class: WSADBench.baseline.MGFN.run.MGFN

parameters:
  dropout: 0.7
  epochs: 100      # 源码写了100，论文没写
  batch_size: 8 # 8个normal和8个异常
  learning_rate: 0.001
  weight_decay:  0.0005
  depths: [3, 3, 2]  # 不写tuple，写list
  mgfn_types: ['gb', 'fb', 'fb']
  mag_ratio: 0.1
  seg: 32  # 无效
  use_scheduler: true
  scheduler_milestones: [ 33, 66 ]
  is_test: false

  # α = 0 1, k = 3, λ1 = λ2 = 1, λ3 = 0 001.