# RoSAS模型配置文件
# 指定模型类和参数

# 模型类路径
model_class: WSADBench.baseline.RTFM.run.RTFM

# 模型参数
parameters:
  dropout: 0.7
  epochs: 1
  batch_size: 32
  learning_rate: 0.001
  weight_decay:  0.0005
  n_features: 2048
